_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
batch_size:
    value: 64
data_dir:
    value: ./data/cityscapes
epochs:
    value: 10
experiment_id:
    value: model-training
lr:
    value: 0.001
num_workers:
    value: 10
seed:
    value: 42
